"""Second  migration

Revision ID: a8fc7d38847c
Revises: 5dcd6d33da43
Create Date: 2023-03-09 17:55:36.577917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fc7d38847c'
down_revision = '5dcd6d33da43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
